services:
  mongo:
    image: mongo:7
    container_name: fruit-mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: fruit_orders
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: fruit-order-api
    depends_on:
      - mongo
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: fruit_orders
      MONGO_USER: mongo_user
      MONGO_PASSWORD: mongo_pass
    ports:
      - "8080:8080"

volumes:
  mongo_data: